### ISSUE TITLE
Failing tests in build

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Data#1329]
Seeing test failures on appveyor:

```
     1>DispatchToInnerBuildsWithVSTestTarget:
         Build continuing because "ContinueOnError" on the task "MSBuild" is set to "ErrorAndContinue".
Test run for C:\projects\fsharp-data\tests\FSharp.Data.Tests\bin\Release\net461\FSharp.Data.Tests.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Failed   Don't throw exceptions on http error
Error Message:
 System.Net.WebException : Timeout exceeded while getting response
  ----> System.TimeoutException : The operation has timed out.
Stack Trace:
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1341
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at FSharp.Data.Tests.Http.Don't throw exceptions on http error() in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 18
--TimeoutException
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commitWithPossibleTimeout[a](FSharpOption`1 res)
   at <StartupCode$FSharp-Core>.$Control.AsyncWaitAsyncWithTimeout@1405-4.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
Failed   Setting timeout in customizeHttpRequest overrides timeout argument
Error Message:
   Expected: 401
  But was:  524
Stack Trace:
   at FsUnit.TopLevelOperators.should[a,a](FSharpFunc`2 f, a x, Object y)
Failed   testFormDataBodySize(4000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: Timeout exceeded while getting response ---> System.TimeoutException: The operation has timed out.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commitWithPossibleTimeout[a](FSharpOption`1 res)
   at <StartupCode$FSharp-Core>.$Control.AsyncWaitAsyncWithTimeout@1405-4.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1341
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1238-2.Invoke(Exception _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 166
Failed   testFormDataBodySize(20000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: Timeout exceeded while getting response ---> System.TimeoutException: The operation has timed out.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commitWithPossibleTimeout[a](FSharpOption`1 res)
   at <StartupCode$FSharp-Core>.$Control.AsyncWaitAsyncWithTimeout@1405-4.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1341
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1238-2.Invoke(Exception _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 166
Failed   testFormDataBodySize(40000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: Timeout exceeded while getting response ---> System.TimeoutException: The operation has timed out.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commitWithPossibleTimeout[a](FSharpOption`1 res)
   at <StartupCode$FSharp-Core>.$Control.AsyncWaitAsyncWithTimeout@1405-4.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1341
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1238-2.Invoke(Exception _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 166
Failed   testFormDataBodySize(100000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: Timeout exceeded while getting response ---> System.TimeoutException: The operation has timed out.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commitWithPossibleTimeout[a](FSharpOption`1 res)
   at <StartupCode$FSharp-Core>.$Control.AsyncWaitAsyncWithTimeout@1405-4.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1341
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1238-2.Invoke(Exception _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 166
Failed   testFormDataBodySize(200000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: Timeout exceeded while getting response ---> System.TimeoutException: The operation has timed out.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commitWithPossibleTimeout[a](FSharpOption`1 res)
   at <StartupCode$FSharp-Core>.$Control.AsyncWaitAsyncWithTimeout@1405-4.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1341
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1238-2.Invoke(Exception _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 166
Failed   testMultipartFormDataBodySize(4000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: Timeout exceeded while getting response ---> System.TimeoutException: The operation has timed out.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commitWithPossibleTimeout[a](FSharpOption`1 res)
   at <StartupCode$FSharp-Core>.$Control.AsyncWaitAsyncWithTimeout@1405-4.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1341
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1238-2.Invoke(Exception _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testMultipartFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 174
Failed   testMultipartFormDataBodySize(20000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: Timeout exceeded while getting response ---> System.TimeoutException: The operation has timed out.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commitWithPossibleTimeout[a](FSharpOption`1 res)
   at <StartupCode$FSharp-Core>.$Control.AsyncWaitAsyncWithTimeout@1405-4.Invoke(Boolean _arg3)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@506-1.Invoke(a a)
   --- End of inner exception stack trace ---
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1341
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1238-2.Invoke(Exception _arg1)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testMultipartFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 174
Failed   testMultipartFormDataBodySize(40000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1342
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1244-3.Invoke(Unit unitVar) in C:\projects\fsharp-data\src\Net\Http.fs:line 1253
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testMultipartFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 174
Failed   testMultipartFormDataBodySize(100000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1342
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1244-3.Invoke(Unit unitVar) in C:\projects\fsharp-data\src\Net\Http.fs:line 1253
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testMultipartFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 174
Failed   testMultipartFormDataBodySize(200000)
Error Message:
   Expected: No Exception to be thrown
  But was:  <System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at FSharp.Data.HttpHelpers.getResponseAsync@1336-4.Invoke(Exception _arg2) in C:\projects\fsharp-data\src\Net\Http.fs:line 1342
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
   at FSharp.Data.HttpHelpers.reraisePreserveStackTrace[a](Exception e) in C:\projects\fsharp-data\src\Net\Http.fs:line 1235
   at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1244-3.Invoke(Unit unitVar) in C:\projects\fsharp-data\src\Net\Http.fs:line 1253
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
Stack Trace:
   at FSharp.Data.Tests.Http.testMultipartFormDataBodySize(Int32 size) in C:\projects\fsharp-data\tests\FSharp.Data.Tests\Http.fs:line 174
Total tests: 2488. Passed: 2476. Failed: 12. Skipped: 0.
Test Run Failed.
Test execution time: 4.8617 Minutes
         Build continuing because "ContinueOnError" on the task "MSBuild" is set to "ErrorAndContinue".
     1>Done Building Project "C:\projects\fsharp-data\tests\FSharp.Data.Tests\FSharp.Data.Tests.fsproj" (VSTest target(s)) -- FAILED.
```

**Comment by dsyme** [comment]
```
Failed   Setting timeout in customizeHttpRequest overrides timeout argument
Error Message:
   Expected: 401
  But was:  524
```

**Comment by nhirschey** [comment]
The build failure might have resolved itself. ``.\build.cmd All`` completes on my machine, and https://github.com/fsharp/FSharp.Data/pull/1334 shows it working on appveyor.
