### ISSUE TITLE
Memory Limitations in XmlProvider

### ISSUE THREAD

**Issue by ibrahim324** [fsprojects/FSharp.Data#1501]
I tried to parse a dump of some wikipedia pages with XmlProvider, but no matter what I try, I get a 
`System.OutOfMemoryException`. Is there some guidance/pattern on how to parse large files with type providers?
The file is almost exactly 2 GB large.

my code:

```
#r "nuget: FSharp.Data"
open FSharp.Data

open System
open System.IO

type Wiki = XmlProvider<"""data/wikidata_sample.xml""">


let xmlFromFile = 
    task{
        let path = "data/wikidata.xml" 
        let! text = File.ReadAllTextAsync(path)
        
        Wiki.Parse(text).Pages
        |> Array.map (fun f -> f.Revision.Text)
        |> Array.iter (fun f -> printfn $"{f}")
    }

let xmlFromStream = 
    let options = 
        new FileStreamOptions(BufferSize=32)
    use stream = new FileStream("data/wikidata.xml", options)
    stream 
    |> Wiki.Load
    |> fun f -> f.Pages
    |> Array.map (fun f -> f.Revision.Text.Value)
    |> Array.iter (fun f -> printfn $"{f}")

xmlFromStream

// xmlFromFile 
// |> Async.AwaitTask
// |> Async.RunSynchronously
```

**Comment by cartermp** [comment]
Can you post the stack trace when this happens?

**Comment by ibrahim324** [comment]
this is the complete error message (copied from fsi):
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at FSharp.Data.Runtime.BaseTypes.XmlElement.Create(TextReader reader) in D:\a\FSharp.Data\FSharp.Data\src\FSharp.Data.Xml.Core\XmlRuntime.fs:line 59
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in /Users/halilibrahimozcan/source/projects/fsharp_xml_parsing/script.fsx:line 25
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Aufgrund eines Fehlers beendet
```

Any other way to retrieve info about the error?

**Comment by cartermp** [comment]
Thanks! In this case it seems the size of the string is too big, as this is failing with the internal `StringBuilder` used in the XML Reader. Are you running in a 32-bit process?

**Comment by ibrahim324** [comment]
@cartermp No, I have not configured fsi in any way. I'm running on MacOS if that makes a difference.

**Comment by Thorium** [comment]
Does it matter if the source file encoding is UTF8 or UTF16 ?

**Comment by ibrahim324** [comment]
@Thorium Can you point to where I should set the encoding? I tried the following:
`let text = File.ReadAllText(path, Encoding.UTF32)`
which didn't work, unfortunately. UTF16 wasn't available either.

**Comment by Thorium** [comment]
I meant if you have the file as XML, if it's UTF16 then consider converting it to UTF8 to use less memory, e.g. Notepad++ tells you:
![image](https://github.com/fsprojects/FSharp.Data/assets/229355/55276843-59a5-4dd7-a848-5d4393ff1991)

**Comment by ibrahim324** [comment]
@Thorium Hi, I just opened it in Notepad++; The file was encoded in UTF-8 to begin with.

**Comment by dsyme** [comment]
Try using `fsiAnyCpu` - `fsi` runs 32-bit by default

**Comment by ibrahim324** [comment]
@dsyme That doesn't seem to be the issue - i ran the script within Rider, which is anycpu by default as I checked. I also ran a console program, but it's still an OutOfMemoryException.
