### ISSUE TITLE
Could not load FSharp.Data.Xml.Core

### ISSUE THREAD

**Issue by halcwb** [fsprojects/FSharp.Data#1519]
When using the FSharp.Data xml provider, everything works fine in a script file. But when I use the EXACT SAME CODE in a normal fs file, compile an run, I get:

System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Data.Xml.Core, Version=6.
4.0.0, Culture=neutral, PublicKeyToken=49286adf818aa259'. The system cannot find the file specifie
d.
File name: 'FSharp.Data.Xml.Core, Version=6.4.0.0, Culture=neutral, PublicKeyToken=49286adf818aa25
9'
   at Informedica.MV6.Lib.Microbiology.getMicrobioloby(Context ctx, String hn)
   at <StartupCode$FSI_0005>.$FSI_0005.main@() in c:\Development\DataServices\src\Informedica.MV6.
Lib\Scripts\Microbiology2.fsx:line 31
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Bool
ean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Stopped due to error

It seems F# providers are extremely brittle and error prone. And when these errors occur, they are extremely hard to debug and reproduce.

**Comment by halcwb** [comment]
I had to separately reference this in the script file.
